{% set name = "asyncio-helpers" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sci-bots/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3288ac1535b0f7803eec036f72ca899722b8bed6ff07f319d8dbb2665cfe3427

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - logging-helpers
    - python >=2.7,<3.7
    - trollius

test:
  imports:
    - asyncio_helpers

about:
  home: http://github.com/sci-bots/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Helper functions, etc. for asyncio development'

extra:
  recipe-maintainers:
    - cfobel
