travis:
  secure:
    BINSTAR_TOKEN: rjwN3q/7rSju5t0WsfrkFTknVEGE2iMSF//V35Q/XteQz2zDjSrjsNN79hOxH0KCH7vcVb6tkHswGpNOzguRe7aYkP+a6CBVZQW5C2WyUwqUbDtF/K1s8DYQCqc7prWH6R+wY7bDXcRoqgq/X+l3Q7/TuLplN5JSSfD8cF8zyYpH4kSnVtUny5t0JsbgI1x58ew6zGEl+V48QDfB/0wpy1OWSuHS0q1dzuQLR7IDX5WYpT5LZ8JvKokRg9fgONEZ8k5jTHSXFIuh9eWsADiby/otDDRuAodE8hRFdnjM0Ynjq3mmVg0E1GRjP954eNsNyCMK7oHUj0aDtmh8Wtv3Rhq3e9nM64Gs1dht9KmJP3Xxs13pRdx33lMofncF+72BBtzBf9JXGlb1KRCnrws8/Iv+ZKZEDopiFi60NJZKb+8w2+ldlYh+ioyMmoAjD9/Dxw7TkeCqzq4CXHAx8GgUPGSxRuNmkePFTEWB+bfu5Dhy6QdkTGxP5jN8k9pcDVeRG8CVAvOiZXvFE47CU4qwx4HUxAaJn+qpDXS0J7GFUO4Oya2jdRfTnaGb0nRH+LW44RaPFPeipqgT9FElksjZ4PXCQM11mYs/7UHE/5JQoKW6fc9aO/2WBGAtfvA+sFdf4XbNeblyIv7y8zpnOdkx0FjqDvtRq5DmTuA2dUHRbXg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
