travis:
  secure:
    BINSTAR_TOKEN: lL1GRN5Y8LXMJ/dzWVavI8TcsgUej9ulEIpuf51xj4HmpUYf94/rxn+YIV4Wsol3MFL0FX7rqKOwKfUBNzV6AmRAvt8m5U3Q+i3ECHkQ3RjCiZM6ckyjcM/2GTCo53UJOJzwJml/+c+9a9JZyh4jPSQquF4B6ge5Uh0OYSwINZ6MoAPJLytnxhT2HE5iNdn+Szr8LfqtZ2oVOpsgTyRzSxFzMcPOJneuY1mXf6MSFtON71i3hrvJF+jHD8yyQl/FJkAyLM+PDgHuX9R+Zh14YfVMN3hk7bdn9emzXYpGbCJ81TMRQE6dgHas64xsRtN1/RAzmND5320JElYue5tWgIOuVSl03bkt4+HtKdL4JVpO5TeQH0Q9I/UjHPaZh39MFCxm1DZqh/Hwn0PJXtQk/WGrfnFYgy2p8HwSkLWMV0Ya4Gc2F8vOqhD6nvcRFpBnljEvNXKJ27A8NzTpV3aVJ+e1lOzvI0GMJNAdN3mL6N6kihd9wrWaY1vkErPvOOavpSBMmAnyYmFxzltgQ/NL/O7IFm2nh/wqA0K7tRmhuhresSH6RRTHdD5PownB0RTaQnUmpquZj931xDS2WV/8BTlVg3ycb2T6khdgvoqVCF1KHGaaEpJDjdY0q+x+sLt8L6arIFLbvQ47ZCuwCVTGqHti178hclRHxBo7qlWvxIw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
